### ISSUE TITLE
Error executing "HeadObject" ; AWS HTTP error: cURL error 6: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by demesiooliveira** [stechstudio/laravel-zipstream#78] opened 2022-08-16 18:40 UTC
Hello guys!

I'm trying to generate a zip file with several images (about 5000) that are S3. They arrive at a time when a HeadObject error pops even though the file exists, has anyone gone through this?

````
ERROR: Error executing "HeadObject" on "https://xpto.s3.us-west-2.amazonaws.com/imagem/img-1789ee4b-0040-4f3d-8760-b683506e65a8.jpg"; AWS HTTP error: cURL error 6: getaddrinfo() thread failed to start
 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xpto.s3.us-west-2.amazonaws.com/imagem/img-1789ee4b-0040-4f3d-8760-b683506e65a8.jpg {"userId":1,"exception":"[object] (Aws\\S3\\Exception\\S3Exception(code: 0): Error executing \"HeadObject\" on \"https://xpto.s3.us-west-2.amazonaws.com/imagem/img-1789ee4b-0040-4f3d-8760-b683506e65a8.jpg\"; AWS HTTP error: cURL error 6: getaddrinfo() thread failed to start
 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xpto.s3.us-west-2.amazonaws.com/imagem/img-1789ee4b-0040-4f3d-8760-b683506e65a8.jpg at /home/ubuntu/apps/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)

````

I believe this is happening due to the large amount of files, is there any way to put this with a chunk?

````
public function downloadFiles(ExportacaoEntrega $exportacao)
{
   
    $zip = Zip::create($exportacao->descricao .'.zip');

        foreach ($exportacao->imagens as $imagem) {

            try {
                $protocolo = 's3://';
                $bucket = env('AWS_BUCKET');
                $filePath = Storage::disk('s3')->path($imagem->source . $imagem->nome);

                $path = $protocolo . $bucket .'/'. $filePath;

                $zip->add($path,  $exportacao->descricao .'/'.$equipamento->id .'/'. $imagem->nome);
                
            }
            catch (\Exception $e) {
                Log::error("unable to read the file at storage path: $imagem->nome and output to zip stream. Exception is " . $e->getMessage());
            }
        }
            
    return $zip;
}
````

**Comment by jszobody** [comment] 2022-08-16 18:46
Do you know the size of your files (say, from a database record)? The `HeadObject` call is attempting to lookup the filesize using the S3 API. If you already have the size you can cut down the number of S3 API calls significantly. 

I don't think the S3 API provides any way to get these filesize or retrieve the file contents in chunks.

**Comment by demesiooliveira** [comment] 2022-08-17 12:54
> Você sabe o tamanho de seus arquivos (digamos, de um registro de banco de dados)? A `HeadObject`chamada está tentando pesquisar o tamanho do arquivo usando a API do S3. Se você já tiver o tamanho, poderá reduzir significativamente o número de chamadas de API do S3.
> 
> Não acho que a API do S3 forneça uma maneira de obter esses tamanhos de arquivo ou recuperar o conteúdo do arquivo em partes.

@jszobody from what I've seen AWS is identifying the amount of request as a DDoS attack so it's refusing the request. I tried using `ZIPSTREAM_PREDICT_SIZE=false` but I still get the same error. Any idea how to solve it?

**Comment by coatezy** [comment] 2022-08-30 20:05
Hey @jszobody!

I am also experiencing a similar issue, I am looping though items in a database but when I hit the 79's item I get the following exception.

```
Error executing "HeadObject" on "https://bucket-name.s3.eu-west-2.amazonaws.com/path/to/file"; AWS HTTP error: cURL error 6: Could not resolve host: bucket-name.s3.eu-west-2.amazonaws.com
```

If I limit the items to 78 the downloads complete. I have confirmed it is not the 79th file itself causing the issue.|

The looking back through the stack trace the error is happening [here](https://github.com/stechstudio/laravel-zipstream/blob/cece761f5ed4a2af51c295f187f6679ad13dfe12/src/Models/S3File.php#L22).

<img width="836" alt="Screenshot 2022-08-30 at 21 00 53" src="https://user-images.githubusercontent.com/2954283/187531974-bb24d7c4-a7d8-430c-9179-3904b47cef9d.png">

Unfortunately I do not have the file size to hand to set the Content-Length.

Hopefully not rate limit related and something simple.

Thanks!
Tom

**Comment by jszobody** [comment] 2022-08-30 20:14
@coatezy That error message shows that curl can't connect to S3. That's a low-level issue with your server not being able to resolve and connect, and is way outside anything that this package is doing.

**Comment by coatezy** [comment] 2022-08-30 20:39
@jszobody This was my initial thought, but the fact it consistently failed on the 79th item made me think it may have been an AWS rate limit issue, although the response did not reflect what I would have expected to see though, and as per the AWS docs these numbers are well within the thresholds. 

https://aws.amazon.com/premiumsupport/knowledge-center/s3-503-within-request-rate-prefix/

I'll continue to investigate at a lower level. 👍

**Comment by jszobody** [comment] 2022-08-30 20:54
@coatezy Are all of your files in the same bucket? Is it possible that the bucket name is different on file 79?

**Comment by coatezy** [comment] 2022-08-31 09:40
@jszobody It may have been an `artisan serve` related issue. I set up the app within Sail and I am no longer seeing this issue.

Out of interest, how long should it take for a download to start? With 200 files it is taking approx 35 seconds with or without the ZIPSTREAM_PREDICT_SIZE=false env variable set. I was expecting the stream to begin instantly either way? It's not a db bottleneck as I can return the paths of all files in a couple hundred ms.

Thanks for you help!

**Comment by jszobody** [comment] 2022-08-31 12:54
> Out of interest, how long should it take for a download to start?

It should start instantly _once it has all the file sizes_. This is again where having those in your local DB would be a lifesaver. Otherwise you have 200 API calls to S3 to get all the file sizes, and that slows things down.

**Comment by jszobody** [comment] 2022-09-01 20:16
I'm going to close this for now, since it seems like it was an `artisan serve` issue.

**Closed by jszobody** 2022-09-01 20:16 UTC
